name: bloc_weigh_in
description: "A weight tracker app focused on average weight over time."
publish_to: "none"
version: 1.0.1+10

environment:
  sdk: ^3.5.1

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^20.1.0
  flutter_timezone: ^5.0.0
  intl: ^0.20.2
  path: ^1.9.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  timezone: ^0.10.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
